#define PERIPH_BASE         (0x40000000UL)
#define AHB1_PERIPH_OFFSET  (0x20000UL)
#define AHB1_PERIPH_BASE    (PERIPH_BASE + AHB1_PERIPH_BASE)
#define GPIOA_OFFSET        (0X0000UL)

#define GPIOA_BASE          (AHB1_PERIPH_BASE + GPIOA_OFFSET)

#define RCC_OFFSET          (0x3800UL)
#define RCC_BASE            (AHB1_PERIPH_BASE + RCC_OFFSET)
